name: Update Stdlib Dependency Graph

on:
    workflow_dispatch:
    schedule:
        -   cron: '30 8,20 * * *' # Run everyday at 8.30 AM and 8.30 PM
    push:
        branches:
          - main
        paths:
          - 'release/resources/module_list.json'

jobs:
    dependency:
        name: Derive module dependencies
        runs-on: ubuntu-latest
        steps:
            -   name : Checkout Repo
                uses: actions/checkout@v2
                with:
                    token: ${{ secrets.BALLERINA_BOT_TOKEN }}

            -   name: Configure Git User
                run: |
                    git config --global user.name ${{ secrets.BALLERINA_BOT_USERNAME }}
                    git config --global user.email ${{ secrets.BALLERINA_BOT_EMAIL }}


            -   name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.x'

            -   name: Install Python packages
                run: |
                    pip install requests
                    pip install networkx
                    pip install retry
                    pip install PyGithub
                    pip install semver

            -   name: Get Dependencies and update files
                run: |
                    python release/src/module_dependencies/update_version_data.py
                env:
                    packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                    packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}

            -   name : Commit files
                run: |
                    git commit -am "[AUTOMATED] Update the Dependency Graph and Dashboard"
                    git push
